// Generated by dts-bundle-generator v9.5.1

declare function registerProxyDomains(domains: string): void;
export declare const sdpppSDK: {
	init(): Promise<import("@modelcontextprotocol/sdk/client/index.js").Client<{
		method: string;
		params?: {
			[x: string]: unknown;
			_meta?: {
				[x: string]: unknown;
				progressToken?: string | number | undefined;
			} | undefined;
		} | undefined;
	}, {
		method: string;
		params?: {
			[x: string]: unknown;
			_meta?: {
				[x: string]: unknown;
			} | undefined;
		} | undefined;
	}, {
		[x: string]: unknown;
		_meta?: {
			[x: string]: unknown;
		} | undefined;
	}>>;
	stores: {
		PhotoshopStore: import("zustand").StoreApi<{
			uname: string;
			activeDocumentID: number;
			documents: Record<number, {
				id: number;
				name: string;
				identify: string;
				layers: {
					id: number;
					name: string;
					identify: string;
					level: number;
					fullPath: string;
					dirtyID: number;
				}[];
				canvasDirtyID: number;
				selectionDirtyID: number;
			}>;
			actions: string[];
			theme: string;
			contentWebviewFocusing: boolean;
			sdpppX?: any;
		}>;
		WebviewStore: import("zustand").StoreApi<{}>;
	};
	plugins: {
		replicateProxy: {
			prediction: {
				create: (data: {
					apiKey: string;
					model: string;
					version: string;
					input: Record<string, any>;
				}) => Promise<any>;
				get: (data: {
					apiKey: string;
					id: string;
				}) => Promise<any>;
				cancel: (data: {
					apiKey: string;
					id: string;
				}) => Promise<boolean>;
			};
			models: {
				get: (data: {
					apiKey: string;
					modelProvider: string;
					modelId: string;
				}) => Promise<any>;
			};
		};
		uxp: {
			openExternalLink: (url: string) => Promise<boolean>;
			removeItem: (key: string) => Promise<boolean>;
			getItem: (key: string) => Promise<any>;
			setItem: (key: string, value: any) => Promise<boolean>;
		};
		fetchProxy: {
			registerProxyDomains: typeof registerProxyDomains;
		};
		imaging: {
			requestImageGet: () => Promise<{
				thumbnail_url: string;
				file_token: string;
				source: string;
			}>;
			requestImageSend: (url: string, source: string) => Promise<void>;
			getBufferByToken: (file_token: string) => Promise<Buffer<ArrayBufferLike>>;
		};
	};
};

export {};
